from help_commands.pythonhelper.import_all import *


def register_dp():
    levels.register_handlers_level(dp)
    mute.register_handlers_mute_file(dp)
    ban.register_handlers_ban(dp)
    reverse.register_reverse_commands(dp)
    view_warns.register_handlers_view_warns(dp)
    warn.register_handlers_warn(dp)
    other_commands.register_handlers_other_commands(dp)
    id_file.register_handlers_id_file(dp)
    hit.register_handlers_hit_command(dp)
    handshake.register_handlers_handshake_command(dp)
    insult.register_handlers_insult_command(dp)
    kiss.register_handlers_kiss_command(dp)
    say.register_handlers_say_command(dp)
    top.register_handlers_top_command(dp)
    sorry.register_handlers_sorry_command(dp)
    tea.register_handlers_tea_command(dp)
    ruletka.register_handlers_ruletka_command(dp)
    whether.register_handlers_whether_command(dp)
    promo.register_handlers_level(dp)
    chatgpt.register_handlers_gpt(dp)
    un_ban.register_handlers_unban(dp)
    vote.register_handlers_report(dp)
    cmd_unwarn.register_handlers_unwarn(dp)
    unmute.register_handlers_unmute(dp)
    spammer.register_handlers_spammer(dp)
    pin.register_handlers_pin_command(dp)
    unpin.register_handlers_pin_command(dp)
    report.register_handlers_report(dp)
    fight.register_handlers_fight(dp)
    give.register_handlers_give_file(dp)
    spam_filter_on.register_handlers_spam_on_filter(dp)
    spam_filter_off.register_handlers_spam_off_filter(dp)
    mats_filter_on.register_handlers_mats_on_filter(dp)
    mats_filter_off.register_handlers_mats_off_filter(dp)
    short_link.register_handlers_shorten_url_command(dp)
    timer.register_handlers_timer_command(dp)
    code.register_handlers_code(dp)
    filter_file.register_handlers_filter_file(dp)
